controller_list:
  - name: fake_bare_arm_controller
    type: $(arg execution_type)
    joints:
      - joint1
      - joint
      - joint3
      - joint4
initial:  # Define initial robot poses.
  - group: bare_arm
    pose: station